### ISSUE TITLE
atm-fraud-detection : error on first KSQL command

### ISSUE THREAD

**Issue by phderome** [confluentinc/demo-scene#37] opened 2018-12-17 14:36 UTC
Invalid primitive column type: STRUCT
(I suspect issues with docker image and possibly related to OSX Mojave environment)

**Comment by rmoff** [comment] 2018-12-17 14:50
Which demo are you running?

**Comment by phderome** [comment] 2018-12-17 14:58
atm-fraud-detection

**Comment by phderome** [comment] 2018-12-17 14:59
ksql> SET 'auto.offset.reset'='earliest';
Successfully changed local property 'auto.offset.reset' from 'null' to 'earliest'
ksql> CREATE STREAM ATM_TXNS (\
>         account_id VARCHAR, \
>         atm VARCHAR, \
>         location STRUCT, \
>         amount INT, \
>         transaction_id VARCHAR) \
>     WITH (\
>         KAFKA_TOPIC='atm_txns', \
>         VALUE_FORMAT='JSON');
Invalid primitive column type: STRUCT

**Comment by rmoff** [comment] 2018-12-17 14:59
How are you running the demo? Are you using the supplied `docker-compose.yml`?

**Comment by phderome** [comment] 2018-12-17 15:02
I ran the docker-compose exec ksql-cli bash command successfully but it failed all day yesterday in that the service and port for ksql was never available and the ksql-server host could not be resolved (yesterday). That's in reference to a github issue I created yesterday and closed today. I am not sure the two issues are related but they may very well be.

docker ps:
MacBook-Pro-3:ksql-atm-fraud-detection philippederome$ docker-compose ps
                    Name                                   Command               State                          Ports                        
---------------------------------------------------------------------------------------------------------------------------------------------
ksql-atm-fraud-detection_connect-debezium_1     /docker-entrypoint.sh bash ...   Up      0.0.0.0:8083->8083/tcp, 8778/tcp, 9092/tcp, 9779/tcp
ksql-atm-fraud-detection_elasticsearch_1        /usr/local/bin/docker-entr ...   Up      0.0.0.0:9200->9200/tcp, 9300/tcp                    
ksql-atm-fraud-detection_gess_1                 python /scripts/gess-main.py     Up                                                          
ksql-atm-fraud-detection_kafka-connect_1        bash -c /etc/confluent/doc ...   Up      0.0.0.0:18083->18083/tcp, 8083/tcp, 9092/tcp        
ksql-atm-fraud-detection_kafka_1                /etc/confluent/docker/run        Up      0.0.0.0:9092->9092/tcp                              
ksql-atm-fraud-detection_kibana_1               bash -c /usr/local/bin/kib ...   Up      0.0.0.0:5601->5601/tcp                              
ksql-atm-fraud-detection_ksql-cli_1             /bin/sh                          Up                                                          
ksql-atm-fraud-detection_ksql-server_1          /etc/confluent/docker/run        Up      0.0.0.0:8088->8088/tcp                              
ksql-atm-fraud-detection_mysql_1                docker-entrypoint.sh mysqld      Up      3306/tcp, 33060/tcp                                 
ksql-atm-fraud-detection_schema-registry_1      /etc/confluent/docker/run        Up      8081/tcp                                            
ksql-atm-fraud-detection_send-gess-to-kafka_1   bash -c nc -v -u -l -p 690 ...   Up      9092/tcp                                            
ksql-atm-fraud-detection_zookeeper_1            /etc/confluent/docker/run        Up      2181/tcp, 2888/tcp, 3888/tcp                        
MacBook-Pro-3:ksql-atm-fraud-detection philippederome$

**Comment by phderome** [comment] 2018-12-17 15:04
see closed issue #36, it might be relevant.

**Comment by rmoff** [comment] 2018-12-17 15:06
@phderome can you post the full console output when you run `docker-compose exec ksql-cli ksql http://ksql-server:8088` ? I'm interested to see the version number.

**Comment by phderome** [comment] 2018-12-17 15:06
docker channel edge 2.0.0.0-mac82 Engine 18.09.00. I am using edge instead of last stable release because of plenty evidence of slowness on web for Mac OS Yosemite users with docker, something I experienced during Confluent's course in November.

**Comment by rmoff** [comment] 2018-12-17 15:07
can you post the full console output when you run `docker-compose exec ksql-cli ksql http://ksql-server:8088` ? I'm interested to see the *KSQL* version number.

**Comment by phderome** [comment] 2018-12-17 15:09
graphics
and then
Copyright 2017-2018 Confluent Inc.

CLI v5.0.1, Server v5.0.1 located at http://ksql-server:8088

Having trouble? Type 'help' (case-insensitive) for a rundown of how things work!

**Comment by rmoff** [comment] 2018-12-17 15:49
From that prompt, can you enter the following, and paste the _full output of the session_ here please: 

1. `LIST TOPICS;`
2. `CREATE STREAM ATM_TXNS (account_id VARCHAR, atm VARCHAR, location STRUCT<lon DOUBLE, lat DOUBLE>, amount INT, timestamp VARCHAR, transaction_id VARCHAR) WITH (KAFKA_TOPIC='atm_txns_gess', VALUE_FORMAT='JSON', TIMESTAMP='timestamp', TIMESTAMP_FORMAT='yyyy-MM-dd HH:mm:ss X');`

**Comment by phderome** [comment] 2018-12-17 15:52
in proper markdown...

```
ksql> LIST TOPICS;

 Kafka Topic        | Registered | Partitions | Partition Replicas | Consumers | ConsumerGroups 
------------------------------------------------------------------------------------------------
 _confluent-metrics | false      | 12         | 1                  | 0         | 0              
 _schemas           | false      | 1          | 1                  | 0         | 0              
 atm_txns_gess      | false      | 1          | 1                  | 0         | 0              
------------------------------------------------------------------------------------------------
ksql> CREATE STREAM ATM_TXNS (account_id VARCHAR, atm VARCHAR, location STRUCT<lon DOUBLE, lat DOUBLE>, amount INT, timestamp VARCHAR, transaction_id VARCHAR) WITH (KAFKA_TOPIC='atm_txns_gess', VALUE_FORMAT='JSON', TIMESTAMP='timestamp', TIMESTAMP_FORMAT='yyyy-MM-dd HH:mm:ss X');

 Message        
----------------
 Stream created 
----------------
ksql> 

```

**Comment by phderome** [comment] 2018-12-17 15:53
so, we need to parameterize explicitly the entries in STRUCT?

**Comment by rmoff** [comment] 2018-12-17 15:54
Ah, right, I think we're getting somewhere. 
Are you running the SQL code from here? https://www.confluent.io/stream-processing-cookbook/ksql-recipes/atm-fraud-detection

**Comment by phderome** [comment] 2018-12-17 15:57
No, from `https://github.com/confluentinc/demo-scene.git`

**Comment by rmoff** [comment] 2018-12-17 15:57
What's the specific URL of the page you copied it from?

**Comment by phderome** [comment] 2018-12-17 15:59
I went to `https://www.confluent.io/blog/atm-fraud-detection-apache-kafka-ksql` then the github url in there: `https://github.com/confluentinc/demo-scene/tree/master/ksql-atm-fraud-detection` and from there I cloned one level up (demo-scene): `https://github.com/confluentinc/demo-scene.git`

**Comment by rmoff** [comment] 2018-12-17 16:02
[Searching the repo](https://github.com/confluentinc/demo-scene/search?q=%22location+STRUCT%22&unscoped_q=%22location+STRUCT%22), the text that you're reporting

             location STRUCT, \

doesn't appear anywhere, so I can only assume it got mangled during copy and paste (for example). 

I'm going to close this now as the issue is resolved. Please re-open if you can find the erroneous SQL (`location STRUCT, \`) somewhere else so that I can fix it.

**Closed by rmoff** 2018-12-17 16:02 UTC

**Comment by phderome** [comment] 2018-12-17 16:04
well https://www.confluent.io/blog/atm-fraud-detection-apache-kafka-ksql has no parameters to STRUCT.

**Comment by rmoff** [comment] 2018-12-17 16:11
Fixed, thanks!
